name: 'SSH action'
description: 'SSHで作成する'
inputs: 
  host: #input id
    description: 'The vps hostname'
    required: true
  username: #input id
    description: 'The vps ssh username'
    required: true
  password: #input id
    description: 'THe vps ssh password'
    required: true
  commands: 
    description: 'The ssh commands'
    required: true
    default: 'ls -h'
runs:
  using: 'node20'
  main: 'index.js'
