name: Test ssh
on:
  push:

jobs:
  sshtest:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ubuntu-latest
    steps:
    - name: Connect ssh and execute command
      uses: kdkwakaba/sshtest@main
      with:
        host: "48.218.35.94"
        username: "azureuser"
        password: ${{ secrets.PASSWORD }}
        commands: |
          pwd
          ls -la
